const axios = require("axios");
const fs = require("fs-extra");
const path = require("path");
const FormData = require("form-data");

module.exports = {
  config: {
    name: "crip",
    version: "2.0",
    author: "Hassan",
    countDown: 10,
    role: 0,
    shortDescription: "Generate AI image",
    longDescription: "Generate a photorealistic image using your own Crip API and upload to Imgur.",
    category: "image",
    guide: "{pn} [your prompt]\nExample: {pn} astronaut dog on mars"
  },

  onStart: async function ({ event, message, args }) {
    const prompt = args.join(" ");
    if (!prompt) {
      return message.reply("❌ Please enter a prompt.\nExample: crip astronaut dog on mars");
    }

    try {
      // Step 1: Generate image with Crip API
      message.reply("🖌️ Generating image with Crip AI...");
      
      const cripApiUrl = "https://hassan-crip-2-o.vercel.app/api/crip";
      const tempDir = path.join(__dirname, "temp");
      
      // Create temp directory if it doesn't exist
      await fs.ensureDir(tempDir);
      
      const timestamp = Date.now();
      const localImagePath = path.join(tempDir, `crip_${timestamp}.png`);
      
      // Generate image
      const response = await axios({
        method: 'POST',
        url: cripApiUrl,
        responseType: 'arraybuffer',
        data: { prompt },
        headers: { 'Content-Type': 'application/json' },
        timeout: 30000 // 30 seconds timeout
      });

      // Save image locally
      await fs.writeFile(localImagePath, response.data);
      
      // Step 2: Upload to Imgur
      message.reply("📤 Uploading image to Imgur...");
      
      const imgurUrl = await uploadToImgur(localImagePath);
      
      if (!imgurUrl) {
        // Fallback: Use base64 if Imgur fails
        message.reply("⚠️ Imgur upload failed, using local storage...");
        const base64Image = await fs.readFile(localImagePath, 'base64');
        const dataUrl = `data:image/png;base64,${base64Image}`;
        
        // Save to message using your system's structure
        return message.reply({
          body: `✅ Generated: "${prompt}"`,
          attachment: localImagePath
        });
      }
      
      // Step 3: Format response for your system
      const formattedMessage = {
        content: `✅ AI Generated Image:\n**Prompt:** "${prompt}"\n📸 Image generated by Crip AI`,
        image_url: imgurUrl,
        generated_by: "crip",
        prompt: prompt
      };
      
      // Clean up temp file
      await fs.remove(localImagePath);
      
      // Return the message object that your system expects
      return message.reply({
        body: formattedMessage.content,
        attachment: imgurUrl // This should work if your system accepts URL attachments
      });
      
    } catch (err) {
      console.error("❌ Crip Command Error:", err.message);
      
      if (err.code === 'ECONNABORTED') {
        return message.reply("⏱️ Image generation timed out. Please try a simpler prompt.");
      }
      
      if (err.response?.status === 429) {
        return message.reply("🚫 Too many requests. Please wait a few minutes before trying again.");
      }
      
      return message.reply("❌ Error generating image. Please try again later.");
    }
  }
};

// Imgur upload function
async function uploadToImgur(imagePath) {
  try {
    const imgurClientId = "225899c9a3312bd"; // Replace with your Imgur Client ID
    // You can get one at: https://api.imgur.com/oauth2/addclient
    
    // Fallback: Use anonymous upload if no client ID
    if (imgurClientId === "YOUR_IMGUR_CLIENT_ID") {
      console.log("⚠️ Using anonymous Imgur upload (limited)");
      return uploadToImgurAnonymous(imagePath);
    }
    
    const formData = new FormData();
    const imageStream = fs.createReadStream(imagePath);
    
    formData.append('image', imageStream);
    formData.append('type', 'file');
    formData.append('title', 'Crip AI Generated Image');
    formData.append('description', 'Generated by Crip AI');
    
    const response = await axios.post('https://api.imgur.com/3/image', formData, {
      headers: {
        'Authorization': `Client-ID ${imgurClientId}`,
        ...formData.getHeaders()
      },
      timeout: 15000
    });
    
    if (response.data.success) {
      return response.data.data.link;
    }
    
    return null;
  } catch (error) {
    console.error("Imgur upload error:", error.message);
    return null;
  }
}

// Anonymous Imgur upload (no client ID required, but limited)
async function uploadToImgurAnonymous(imagePath) {
  try {
    const formData = new FormData();
    const imageStream = fs.createReadStream(imagePath);
    
    formData.append('image', imageStream);
    
    const response = await axios.post('https://api.imgur.com/3/image', formData, {
      headers: {
        'Authorization': 'Client-ID 225899c9a3312bd', // Anonymous client ID
        ...formData.getHeaders()
      },
      timeout: 15000
    });
    
    if (response.data.success) {
      return response.data.data.link;
    }
    
    return null;
  } catch (error) {
    console.error("Anonymous Imgur upload failed:", error.message);
    return null;
  }
}

// Alternative: Upload to Supabase Storage (if you prefer)
async function uploadToSupabaseStorage(imagePath, fileName) {
  try {
    const { supabase } = require('../index.js'); // Adjust path as needed
    
    const fileBuffer = await fs.readFile(imagePath);
    const fileExtension = path.extname(imagePath);
    const uniqueFileName = `crip_${Date.now()}${fileExtension}`;
    const filePath = `ai_images/${uniqueFileName}`;
    
    const { data, error } = await supabase.storage
      .from('chat-images') // Your bucket name
      .upload(filePath, fileBuffer, {
        contentType: 'image/png',
        upsert: false
      });
    
    if (error) throw error;
    
    // Get public URL
    const { data: urlData } = supabase.storage
      .from('chat-images')
      .getPublicUrl(filePath);
    
    return urlData.publicUrl;
  } catch (error) {
    console.error("Supabase upload error:", error);
    return null;
  }
      }
