const fs = require("fs");
const path = require("path");
const fetch = require("node-fetch");

// You MUST replace these with your actual API keys
const IMGUR_CLIENT_ID = "225899c9a3312bd"; // Get from imgur.com
const CLIPDROP_API_KEY = "91c943b1448de009eba2ada63b39c50dc5ded3db61dbd14e2d4970a7edc9e73c04b0e11a0520e04f37ee07fd6dc140e9"; // Get from clipdrop.co

function tmpFile(name = "crip") {
  const id = `${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;
  return path.join(process.cwd(), `${name}_${id}.png`);
}

module.exports = {
  config: {
    name: "crip2",
    version: "1.0",
    author: "Hassan",
    countDown: 30, // Increased timeout for image generation
    role: 0,
    shortDescription: { en: "Generate AI images" },
    longDescription: { 
      en: "Create AI-generated images from text prompts using ClipDrop API" 
    },
    category: "image",
    guide: { en: "!crip <prompt>" }
  },

  onStart: async function ({ api, event, args }) {
    try {
      // Check if user provided prompt
      if (!args.length) {
        return api.sendMessage(
          `📸 Crip AI Image Generator\n\nUsage: !crip <prompt>\nExample: !crip beautiful sunset over mountains\n\n🔑 Required: ClipDrop API key at https://clipdrop.co/`,
          event.threadID,
          event.messageID
        );
      }

      // Check if API keys are set
      if (CLIPDROP_API_KEY === "91c943b1448de009eba2ada63b39c50dc5ded3db61dbd14e2d4970a7edc9e73c04b0e11a0520e04f37ee07fd6dc140e9") {
        return api.sendMessage(
          "❌ Please configure ClipDrop API key first.\nGet free credits: https://clipdrop.co/",
          event.threadID,
          event.messageID
        );
      }

      const prompt = args.join(" ").trim();
      
      // Send initial processing message
      const processingMsg = await api.sendMessage(
        `🔄 Generating image: "${prompt.substring(0, 50)}${prompt.length > 50 ? '...' : ''}"\n⏳ Please wait...`,
        event.threadID,
        event.messageID
      );

      console.log(`[Crip AI] Generating image for: ${prompt}`);
      
      // --- Generate image via ClipDrop API ---
      const clipdropResp = await fetch("https://clipdrop-api.co/text-to-image/v1", {
        method: "POST",
        headers: {
          "x-api-key": CLIPDROP_API_KEY,
          "Content-Type": "application/json"
        },
        body: JSON.stringify({ prompt }),
        timeout: 30000 // 30 second timeout
      });

      if (!clipdropResp.ok) {
        const errorText = await clipdropResp.text();
        console.error("[Crip AI] ClipDrop Error:", errorText);
        throw new Error(`ClipDrop API error: ${clipdropResp.status}`);
      }

      // Get image buffer
      const imageBuffer = await clipdropResp.buffer();
      
      // Check if image is valid
      if (!imageBuffer || imageBuffer.length < 100) {
        throw new Error("Invalid image received from API");
      }

      // Save temporarily
      const tempFilePath = tmpFile();
      fs.writeFileSync(tempFilePath, imageBuffer);
      console.log(`[Crip AI] Image saved: ${tempFilePath} (${Math.round(imageBuffer.length / 1024)}KB)`);

      // --- METHOD 1: Send directly as attachment (no Imgur needed) ---
      // Delete processing message
      if (processingMsg && processingMsg.messageID) {
        await api.unsendMessage(processingMsg.messageID);
      }

      // Send the image directly
      return api.sendMessage(
        {
          body: `✅ Image Generated!\n\n📝 Prompt: "${prompt}"\n🖼️ AI Generated by ClipDrop`,
          attachment: fs.createReadStream(tempFilePath)
        },
        event.threadID,
        event.messageID,
        async () => {
          // Clean up temp file after sending
          try {
            fs.unlinkSync(tempFilePath);
            console.log(`[Crip AI] Cleaned up: ${tempFilePath}`);
          } catch (cleanupError) {
            console.error("[Crip AI] Cleanup error:", cleanupError);
          }
        }
      );

    } catch (error) {
      console.error("[Crip AI] Error:", error);
      
      // Clean up any temp files
      try {
        const tempFiles = fs.readdirSync(process.cwd())
          .filter(file => file.startsWith("crip_") && file.endsWith(".png"));
        
        tempFiles.forEach(file => {
          try { 
            fs.unlinkSync(path.join(process.cwd(), file)); 
            console.log(`[Crip AI] Cleaned orphaned file: ${file}`);
          } catch {}
        });
      } catch {}
      
      return api.sendMessage(
        `❌ Image generation failed.\n\nError: ${error.message}\n\nPossible fixes:\n1. Check your ClipDrop API key\n2. Try a different prompt\n3. Ensure you have API credits\n4. Wait a few minutes and try again`,
        event.threadID,
        event.messageID
      );
    }
  }
};
